# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91b16876d9515e5a1a6c0c6a11fb4abe46ff2fc9282061ec4d7a58f8c239fc0aa0c2d216eb9c1fbad67ceb394dc0ec473807465a9dc40a45d68037a1e5b9b0fb

test:
  secret_key_base: deaa774b830cddf3d3822abd9142d286bf200d461b6c6810d4af70a6360a426c7193d8c69aaa7f5f840978af55a5f7396105b5078ceb6645ead220584744cd0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
